import type { CommandResult, WorkspaceState } from "../runtime/protocol";

export type LessonId = "init" | "manual-revision" | "upgrade-downgrade" | "autogenerate" | "collaboration";

export type LessonDefinition = {
  id: LessonId;
  number: string;
  title: string;
  concept: string;
  instructions: string[];
  example?: { title: string; path: string; description: string; code: string };
};

export type LessonEvidence = {
  initializedObserved: boolean;
  manualRevisionCreated: boolean;
  manualUnappliedObserved: boolean;
  upgradeObserved: boolean;
  downgradeObserved: boolean;
  autogeneratedRevisions: string[];
  reviewedRevisions: string[];
  autogenerateApplied: boolean;
  multipleHeadsErrorObserved: boolean;
};

export type LessonStep = { id: string; label: string; complete: boolean };
export type LessonAssessment = { complete: boolean; steps: LessonStep[] };

type LessonWorkspace = { snapshot?: WorkspaceState; evidence: LessonEvidence };
export type CollaborationContext = {
  baseRevisions: string[];
  filesIntegrated: boolean;
  multipleHeadsObserved: boolean;
  alice?: LessonWorkspace;
  bob?: LessonWorkspace;
  integration?: LessonWorkspace;
};

export const SQLALCHEMY_USER_MODEL_EXAMPLE = `from datetime import datetime

from sqlalchemy import DateTime, MetaData, String, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True)
    display_name: Mapped[str | None] = mapped_column(String(100), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )


# Revision Lab의 env.py가 읽는 target_metadata입니다.
metadata = Base.metadata
`;

export const lessons: LessonDefinition[] = [
  {
    id: "init", number: "01", title: "init과 프로젝트 구조",
    concept: "Alembic 환경 파일과 실제 DB는 서로 다른 상태입니다.",
    instructions: ["alembic init migrations를 실행합니다.", "생성된 alembic.ini, env.py, models.py를 파일 패널에서 확인합니다."],
  },
  {
    id: "manual-revision", number: "02", title: "수동 revision",
    concept: "Revision 파일을 만드는 것만으로 DB schema는 바뀌지 않습니다.",
    instructions: ["alembic revision -m \"create users\"를 실행합니다.", "DAG의 새 head와 base 상태의 DB current를 비교합니다."],
  },
  {
    id: "upgrade-downgrade", number: "03", title: "upgrade와 downgrade",
    concept: "alembic_version과 실제 schema가 migration 실행 방향에 따라 함께 이동합니다.",
    instructions: ["revision의 upgrade()/downgrade()를 편집하고 저장합니다.", "upgrade head 후 schema와 DB current를 확인합니다.", "downgrade -1로 되돌린 뒤 실제 DB 상태를 확인합니다."],
  },
  {
    id: "autogenerate", number: "04", title: "autogenerate 검토",
    concept: "Autogenerate는 현재 DB와 metadata의 차이를 바탕으로 후보를 만들며, 적용 전 검토가 필요합니다.",
    instructions: [
      "파일 패널에서 models.py를 열고 아래 User 모델 예제로 내용을 교체합니다.",
      "파일 저장 또는 Ctrl/⌘+S로 변경 내용을 runtime에 저장합니다.",
      "alembic revision --autogenerate -m \"add users\"를 실행합니다.",
      "생성 파일의 create_table, constraint, index를 검토한 뒤 upgrade head로 적용합니다.",
    ],
    example: {
      title: "models.py · 실무형 SQLAlchemy 2.x User 모델",
      path: "models.py",
      description: "DeclarativeBase와 Mapped 타입을 사용하고 constraint 이름을 안정적으로 만드는 naming convention을 포함합니다. 마지막 metadata 별칭은 Revision Lab의 env.py가 autogenerate 대상으로 읽습니다.",
      code: SQLALCHEMY_USER_MODEL_EXAMPLE,
    },
  },
  {
    id: "collaboration", number: "05", title: "Alice / Bob branch와 merge",
    concept: "서로 다른 revision ID도 같은 부모에서 갈라지면 multiple heads가 됩니다. 같은 ID·파일 경로 충돌과는 다르며, merge revision도 DDL 충돌을 대신 해결하지 않습니다.",
    instructions: ["현재 DB가 하나의 head에 있는 공통 base를 준비합니다.", "Alice/Bob/integration workspace로 복제합니다.", "Alice와 Bob이 각자 revision을 만든 뒤 PR 합치기를 실행합니다.", "integration에서 upgrade head 실패를 확인하고 merge revision을 만든 뒤 다시 upgrade합니다."],
  },
];

export const emptyLessonEvidence = (): LessonEvidence => ({
  initializedObserved: false,
  manualRevisionCreated: false,
  manualUnappliedObserved: false,
  upgradeObserved: false,
  downgradeObserved: false,
  autogeneratedRevisions: [],
  reviewedRevisions: [],
  autogenerateApplied: false,
  multipleHeadsErrorObserved: false,
});

function revisionIds(state: WorkspaceState): Set<string> {
  return new Set(state.revisions.map((revision) => revision.revision));
}

export function recordCommandEvidence(previous: LessonEvidence, result: CommandResult): LessonEvidence {
  const next: LessonEvidence = { ...previous, autogeneratedRevisions: [...previous.autogeneratedRevisions], reviewedRevisions: [...previous.reviewedRevisions] };
  const created = result.after.revisions.filter((revision) => !revisionIds(result.before).has(revision.revision)).map((revision) => revision.revision);
  const command = result.argv[0];
  if (result.success && command === "init" && initialized(result.after)) next.initializedObserved = true;
  if (result.success && command === "revision" && !result.argv.includes("--autogenerate") && created.length > 0) {
    next.manualRevisionCreated = true;
    if (created.every((revision) => !result.after.schema.alembicVersion.includes(revision))) next.manualUnappliedObserved = true;
  }
  if (result.success && command === "upgrade" && result.before.schema.alembicVersion.join("\0") !== result.after.schema.alembicVersion.join("\0")) next.upgradeObserved = true;
  if (result.success && command === "downgrade" && result.before.schema.alembicVersion.join("\0") !== result.after.schema.alembicVersion.join("\0")) next.downgradeObserved = true;
  if (result.success && command === "revision" && result.argv.includes("--autogenerate") && created.length > 0) {
    next.autogeneratedRevisions = [...new Set([...next.autogeneratedRevisions, ...created])];
  }
  if (next.autogeneratedRevisions.some((revision) => result.after.schema.alembicVersion.includes(revision))) next.autogenerateApplied = true;
  if (!result.success && command === "upgrade" && result.before.revisions.filter((revision) => revision.isHead).length > 1) next.multipleHeadsErrorObserved = true;
  return next;
}

export function recordRevisionReview(previous: LessonEvidence, revision?: string): LessonEvidence {
  if (!revision || !previous.autogeneratedRevisions.includes(revision) || previous.reviewedRevisions.includes(revision)) return previous;
  return { ...previous, reviewedRevisions: [...previous.reviewedRevisions, revision] };
}

function initialized(state?: WorkspaceState): boolean {
  if (!state) return false;
  return state.files.includes("alembic.ini") && state.files.includes("models.py") && state.files.some((path) => path.endsWith("/env.py"));
}

function atSingleHead(state?: WorkspaceState): boolean {
  if (!state) return false;
  const heads = state.revisions.filter((revision) => revision.isHead);
  return heads.length === 1 && heads[0]?.isCurrent === true && state.schema.alembicVersion.length === 1;
}

export function canCloneCollaborationBase(state?: WorkspaceState): boolean {
  return initialized(state) && atSingleHead(state);
}

function actorBranched(actor: LessonWorkspace | undefined, baseRevisions: Set<string>): boolean {
  return Boolean(actor?.snapshot?.revisions.some((revision) => !baseRevisions.has(revision.revision)));
}

export function assessLesson(id: LessonId, workspace?: LessonWorkspace, collaboration?: CollaborationContext): LessonAssessment {
  const snapshot = workspace?.snapshot;
  let steps: LessonStep[];
  if (id === "init") {
    steps = [
      { id: "environment", label: "실제 Alembic 환경 파일 생성", complete: Boolean(workspace?.evidence.initializedObserved || initialized(snapshot)) },
      { id: "database", label: "DB와 revision graph를 runtime에서 확인", complete: Boolean(workspace?.evidence.initializedObserved || (initialized(snapshot) && snapshot?.schema.alembicVersion.length === 0)) },
    ];
  } else if (id === "manual-revision") {
    steps = [
      { id: "revision", label: "수동 revision 생성", complete: Boolean(workspace?.evidence.manualRevisionCreated) },
      { id: "head", label: "새 file head를 DAG에서 확인", complete: Boolean(snapshot?.revisions.some((revision) => revision.isHead)) },
      { id: "unapplied", label: "파일 생성과 DB 적용 상태의 차이 확인", complete: Boolean(workspace?.evidence.manualUnappliedObserved ||
        (snapshot?.revisions.length && snapshot.schema.alembicVersion.length < snapshot.revisions.filter((revision) => revision.isHead).length)) },
    ];
  } else if (id === "upgrade-downgrade") {
    steps = [
      { id: "upgrade", label: "실제 upgrade와 DB current 이동 확인", complete: Boolean(workspace?.evidence.upgradeObserved) },
      { id: "downgrade", label: "실제 downgrade와 DB current 이동 확인", complete: Boolean(workspace?.evidence.downgradeObserved) },
    ];
  } else if (id === "autogenerate") {
    const generated = workspace?.evidence.autogeneratedRevisions ?? [];
    steps = [
      { id: "generated", label: "실제 autogenerate revision 생성", complete: generated.length > 0 },
      { id: "reviewed", label: "생성된 migration 파일 열어 검토", complete: generated.some((revision) => workspace?.evidence.reviewedRevisions.includes(revision)) },
      { id: "applied", label: "검토한 revision을 실제 DB에 적용", complete: Boolean(workspace?.evidence.autogenerateApplied) },
    ];
  } else {
    const base = new Set(collaboration?.baseRevisions ?? []);
    const integration = collaboration?.integration;
    const integrationState = integration?.snapshot;
    const heads = integrationState?.revisions.filter((revision) => revision.isHead) ?? [];
    const merge = integrationState?.revisions.find((revision) => revision.isMergePoint);
    steps = [
      { id: "base", label: "하나의 current head를 공통 base로 준비", complete: Boolean(collaboration) || canCloneCollaborationBase(snapshot) },
      { id: "cloned", label: "Alice · Bob · integration을 같은 base에서 복제", complete: Boolean(collaboration?.alice && collaboration.bob && integration) },
      { id: "branches", label: "Alice와 Bob이 독립 revision 생성", complete: actorBranched(collaboration?.alice, base) && actorBranched(collaboration?.bob, base) },
      { id: "heads", label: "PR 합치기 후 실제 multiple heads 확인", complete: Boolean(collaboration?.filesIntegrated && (collaboration.multipleHeadsObserved || heads.length > 1)) },
      { id: "error", label: "integration의 실제 upgrade head 오류 확인", complete: Boolean(integration?.evidence.multipleHeadsErrorObserved) },
      { id: "merge", label: "복수 down_revision의 실제 merge revision 생성", complete: Boolean(merge && merge.downRevisions.length > 1) },
      { id: "resolved", label: "merge head까지 실제 DB upgrade", complete: Boolean(merge?.isCurrent && integrationState?.schema.alembicVersion.includes(merge.revision)) },
    ];
  }
  return { complete: steps.every((step) => step.complete), steps };
}
