import { describe, expect, it } from "vitest";
import { assessLesson, emptyLessonEvidence, recordCommandEvidence, recordRevisionReview } from "./lessons";
import type { CommandResult, RevisionNode, WorkspaceState } from "../runtime/protocol";

function revision(revisionId: string, options: Partial<RevisionNode> = {}): RevisionNode {
  return { revision: revisionId, path: `migrations/versions/${revisionId}.py`, downRevisions: [], branchLabels: [], dependsOn: [],
    isHead: true, isBranchPoint: false, isMergePoint: false, isCurrent: false, ...options };
}

function state(revisions: RevisionNode[] = [], current: string[] = []): WorkspaceState {
  return { files: ["alembic.ini", "models.py", "migrations/env.py"], revisions,
    schema: { dialect: "sqlite", tables: [], alembicVersion: current } };
}

function result(argv: string[], before: WorkspaceState, after: WorkspaceState, success = true): CommandResult {
  return { argv, before, after, success, stdout: "", stderr: "", fileChanges: [],
    schemaDiff: { changes: [], alembicVersion: { before: before.schema.alembicVersion, after: after.schema.alembicVersion } },
    ...(success ? {} : { error: { code: "ALEMBIC_COMMAND_FAILED", message: "Multiple head revisions" } }) };
}

describe("lesson validation", () => {
  it("uses graph and DB transitions to validate manual, upgrade and downgrade lessons", () => {
    const base = state();
    const fileHead = state([revision("r1")]);
    const currentHead = state([revision("r1", { isCurrent: true })], ["r1"]);
    let evidence = recordCommandEvidence(emptyLessonEvidence(), result(["revision", "-m", "anything"], base, fileHead));
    evidence = recordCommandEvidence(evidence, result(["upgrade", "head"], fileHead, currentHead));
    evidence = recordCommandEvidence(evidence, result(["downgrade", "-1"], currentHead, fileHead));
    expect(assessLesson("manual-revision", { snapshot: fileHead, evidence }).complete).toBe(true);
    expect(assessLesson("upgrade-downgrade", { snapshot: fileHead, evidence }).complete).toBe(true);
  });

  it("requires an actual autogenerated revision, review and DB application", () => {
    const before = state([revision("r1", { isCurrent: true })], ["r1"]);
    const generated = state([
      revision("r2", { downRevisions: ["r1"] }),
      revision("r1", { isHead: false, isCurrent: true }),
    ], ["r1"]);
    const applied = state([
      revision("r2", { downRevisions: ["r1"], isCurrent: true }),
      revision("r1", { isHead: false }),
    ], ["r2"]);
    let evidence = recordCommandEvidence(emptyLessonEvidence(), result(["revision", "--autogenerate", "-m", "models"], before, generated));
    evidence = recordRevisionReview(evidence, "r2");
    evidence = recordCommandEvidence(evidence, result(["upgrade", "head"], generated, applied));
    expect(assessLesson("autogenerate", { snapshot: applied, evidence }).complete).toBe(true);
  });

  it("accepts collaboration only after the real branch graph, error, merge and current DB agree", () => {
    const baseRevision = revision("base", { isCurrent: true });
    const actor = (id: string) => ({ snapshot: state([revision(id, { downRevisions: ["base"] }), { ...baseRevision, isHead: false }], ["base"]), evidence: emptyLessonEvidence() });
    const merge = revision("merge", { downRevisions: ["alice", "bob"], isMergePoint: true, isCurrent: true });
    const integration = {
      snapshot: state([merge, revision("alice", { downRevisions: ["base"], isHead: false }), revision("bob", { downRevisions: ["base"], isHead: false }), { ...baseRevision, isHead: false, isCurrent: false }], ["merge"]),
      evidence: { ...emptyLessonEvidence(), multipleHeadsErrorObserved: true },
    };
    expect(assessLesson("collaboration", undefined, {
      baseRevisions: ["base"], filesIntegrated: true, multipleHeadsObserved: true,
      alice: actor("alice"), bob: actor("bob"), integration,
    }).complete).toBe(true);
  });
});
