import { createStore } from "zustand/vanilla";
import { AlembicRuntimeClient, runtimeFault } from "../runtime/alembic-runtime-client";
import type { CommandResult, DatabaseMode, FileChange, RpcFault, RuntimeCloneSeed, TableData, WorkspaceState } from "../runtime/protocol";
import {
  canCloneCollaborationBase, emptyLessonEvidence, recordCommandEvidence, recordRevisionReview,
  type LessonEvidence, type LessonId,
} from "../lessons/lessons";
import {
  createCheckpointRepository, type CheckpointRepository, type PersistedSession, type WorkspaceCheckpoint,
} from "../persistence/checkpoints";
import { createWorkspaceArchive, type WorkspaceArchiveV1 } from "../persistence/workspace-archive";

export type Panel = "editor" | "graph" | "database" | "diff" | "logs";
export type Draft = { text: string; saved: string };
export type Entry = { id: number; command: string; result?: CommandResult; error?: RpcFault };
export type Workspace = {
  id: string; name: string; mode: DatabaseMode; snapshot?: WorkspaceState;
  drafts: Record<string, Draft>; file?: string; revision?: string; table?: string;
  data?: TableData; entries: Entry[]; changes: FileChange[]; result?: CommandResult;
  error?: RpcFault; broken: boolean; stale: boolean; savedAt?: number; recoveredAt?: number;
  evidence: LessonEvidence; role?: "base" | "alice" | "bob" | "integration"; collaborationId?: string;
};
export type Collaboration = {
  id: string; baseId: string; baseRevisions: string[]; aliceId: string; bobId: string; integrationId: string;
  filesIntegrated: boolean; multipleHeadsObserved: boolean;
};
export type LabState = {
  workspaces: Workspace[]; activeId?: string; busy: boolean; progress: string; panel: Panel;
  guideEnabled: boolean; activeLesson: LessonId; collaboration?: Collaboration; restoring: boolean;
};
export type LabClient = Pick<AlembicRuntimeClient, "createWorkspace" | "exportClone" | "readFile" | "writeFile" | "runCommand" | "readTable" |
  "close" | "onProgress" | "onFailure"> & Partial<Pick<AlembicRuntimeClient, "destroy" | "forceCrashForTest">>;
export type ClientFactory = (mode: DatabaseMode, id: string, seed?: RuntimeCloneSeed) => LabClient;

const evidenceKeys: Array<keyof LessonEvidence> = [
  "initializedObserved", "manualRevisionCreated", "manualUnappliedObserved", "upgradeObserved", "downgradeObserved",
  "autogeneratedRevisions", "reviewedRevisions", "autogenerateApplied", "multipleHeadsErrorObserved",
];

function encodeEvidence(evidence: LessonEvidence): Record<string, string> {
  return Object.fromEntries(evidenceKeys.map((key) => [key, JSON.stringify(evidence[key])]));
}

function decodeEvidence(progress: Record<string, string>): LessonEvidence {
  const evidence = emptyLessonEvidence();
  for (const key of evidenceKeys) {
    const encoded = progress[key];
    if (encoded === undefined) continue;
    try {
      const value: unknown = JSON.parse(encoded);
      if ((key === "autogeneratedRevisions" || key === "reviewedRevisions") && Array.isArray(value) && value.every((item) => typeof item === "string")) evidence[key] = value;
      else if (key !== "autogeneratedRevisions" && key !== "reviewedRevisions" && typeof value === "boolean") evidence[key] = value;
    } catch { /* Ignore optional lesson progress that cannot be decoded. */ }
  }
  return evidence;
}

function base64ToArrayBuffer(source: string): ArrayBuffer {
  const binary = atob(source);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
  return bytes.buffer;
}

function arrayBufferToBase64(source: ArrayBuffer): string {
  const bytes = new Uint8Array(source);
  let binary = "";
  for (let offset = 0; offset < bytes.length; offset += 32_768) binary += String.fromCharCode(...bytes.subarray(offset, Math.min(offset + 32_768, bytes.length)));
  return btoa(binary);
}

function persistenceFault(error: unknown, code = "PERSISTENCE_FAILED"): RpcFault {
  return { code, message: error instanceof Error ? error.message : String(error) };
}

export function createLab(
  factory: ClientFactory = (mode, id, seed) => new AlembicRuntimeClient(mode, id, seed),
  repository: CheckpointRepository = createCheckpointRepository(),
) {
  const store = createStore<LabState>(() => ({
    workspaces: [], busy: false, progress: "Workspace를 만들어 실습을 시작하세요.", panel: "editor",
    guideEnabled: false, activeLesson: "init", restoring: false,
  }));
  const clients = new Map<string, LabClient>();
  const recovering = new Set<string>();
  let entryId = 0;
  let workspaceNumber = 0;
  let disposed = false;
  let persistenceQueue: Promise<unknown> = Promise.resolve();
  const active = () => store.getState().workspaces.find((item) => item.id === store.getState().activeId);
  const patch = (id: string, update: Partial<Workspace>) => store.setState((state) => ({ workspaces: state.workspaces.map((item) => item.id === id ? { ...item, ...update } : item) }));
  const session = (): PersistedSession => {
    const state = store.getState();
    return { formatVersion: 1, workspaceIds: state.workspaces.map((workspace) => workspace.id), activeId: state.activeId,
      panel: state.panel, guideEnabled: state.guideEnabled, activeLesson: state.activeLesson, collaboration: state.collaboration };
  };
  const enqueuePersistence = <T,>(operation: () => Promise<T>): Promise<T> => {
    const result = persistenceQueue.then(operation, operation);
    persistenceQueue = result.then(() => undefined, () => undefined);
    return result;
  };
  const saveSession = () => enqueuePersistence(() => repository.saveSession(session())).catch((error) => {
    const workspace = active();
    if (workspace) patch(workspace.id, { error: persistenceFault(error, "CHECKPOINT_SESSION_FAILED") });
  });
  const fail = (id: string, error: unknown) => {
    const fault = runtimeFault(error);
    const broken = /TIMEOUT|WORKER_CRASH|RUNTIME_CLOSED|BOOT_FAILED|INVALID_RESPONSE/.test(fault.code);
    patch(id, { error: fault, broken: broken || Boolean(store.getState().workspaces.find((item) => item.id === id)?.broken), stale: true, data: undefined });
    return fault;
  };
  const bind = (id: string, client: LabClient, label?: string, autoRecover = true) => {
    client.onProgress = (progress) => store.setState({ progress: label ? `${label} · ${progress}` : progress });
    client.onFailure = (fault) => {
      patch(id, { error: fault, broken: true, stale: true, data: undefined });
      if (autoRecover) window.setTimeout(() => { if (!disposed) void recoverWorkspace(id); }, 0);
    };
  };
  const checkpoint = async (id: string): Promise<void> => {
    const workspace = store.getState().workspaces.find((item) => item.id === id);
    const client = clients.get(id);
    if (!workspace || !client || workspace.broken) return;
    store.setState({ progress: "마지막 성공 체크포인트 저장 중" });
    try {
      const savedAt = Date.now();
      const exported = await client.exportClone();
      const seed = exported.pgliteDatabase instanceof Blob
        ? { ...exported, pgliteDatabase: await exported.pgliteDatabase.arrayBuffer() }
        : exported;
      const record: WorkspaceCheckpoint = {
        formatVersion: 1,
        workspace: { id, name: workspace.name, mode: workspace.mode, evidence: workspace.evidence, role: workspace.role,
          collaborationId: workspace.collaborationId, file: workspace.file, revision: workspace.revision, entries: workspace.entries.slice(-20) },
        seed, savedAt,
      };
      await enqueuePersistence(() => repository.save(record, session()));
      patch(id, { savedAt, recoveredAt: undefined });
    } catch (error) {
      patch(id, { error: persistenceFault(error, "CHECKPOINT_SAVE_FAILED") });
    }
  };
  const perform = async (operation: (workspace: Workspace, client: LabClient) => Promise<void>) => {
    const workspace = active();
    if (!workspace || workspace.broken || store.getState().busy) return;
    const client = clients.get(workspace.id);
    if (!client) return;
    store.setState({ busy: true, progress: "요청 처리 중" });
    patch(workspace.id, { error: undefined });
    try { await operation(workspace, client); }
    catch (error) { fail(workspace.id, error); }
    finally { store.setState({ busy: false, progress: "요청 처리 완료" }); }
  };
  const loadFile = async (workspace: Workspace, client: LabClient, path: string, refresh = false) => {
    const current = store.getState().workspaces.find((item) => item.id === workspace.id) ?? workspace;
    const draft = current.drafts[path];
    if (!draft || (refresh && draft.text === draft.saved)) {
      const content = await client.readFile(path);
      patch(workspace.id, { drafts: { ...current.drafts, [path]: { text: content, saved: content } }, file: path });
    } else patch(workspace.id, { file: path });
  };
  const workspaceFromCheckpoint = (record: WorkspaceCheckpoint, snapshot?: WorkspaceState): Workspace => ({
    id: record.workspace.id, name: record.workspace.name, mode: record.workspace.mode, snapshot,
    drafts: {}, entries: record.workspace.entries ?? [], changes: [], result: record.workspace.entries?.at(-1)?.result,
    file: record.workspace.file, revision: record.workspace.revision, broken: false, stale: false,
    savedAt: record.savedAt, evidence: record.workspace.evidence ?? emptyLessonEvidence(), role: record.workspace.role,
    collaborationId: record.workspace.collaborationId,
  });
  const recoverWorkspace = async (id: string): Promise<void> => {
    if (recovering.has(id) || disposed) return;
    if (store.getState().busy) { window.setTimeout(() => { if (!disposed) void recoverWorkspace(id); }, 25); return; }
    const workspace = store.getState().workspaces.find((item) => item.id === id);
    if (!workspace?.broken) return;
    recovering.add(id);
    store.setState({ busy: true, progress: `${workspace.name} 체크포인트 복원 중` });
    try {
      const saved = await repository.loadCheckpoint(id);
      if (!saved) {
        const original = store.getState().workspaces.find((item) => item.id === id)?.error;
        patch(id, { error: original ? { ...original, message: `${original.message}\n마지막 성공 체크포인트가 없어 자동 복원할 수 없습니다.` }
          : { code: "CHECKPOINT_NOT_FOUND", message: "마지막 성공 체크포인트가 없어 자동 복원할 수 없습니다." } });
        return;
      }
      clients.get(id)?.close();
      const seed = saved.workspace.mode === "postgresql" ? { ...saved.seed, reusePgliteDatabase: true } : saved.seed;
      const client = factory(saved.workspace.mode, id, seed);
      clients.set(id, client);
      bind(id, client, undefined, false);
      const snapshot = await client.createWorkspace();
      bind(id, client);
      const restored = workspaceFromCheckpoint(saved, snapshot);
      patch(id, { ...restored, recoveredAt: Date.now(), error: undefined });
      if (restored.file && snapshot.files.includes(restored.file)) await loadFile(restored, client, restored.file);
      await enqueuePersistence(() => repository.saveSession(session()));
    } catch (error) {
      fail(id, error);
    } finally {
      recovering.delete(id);
      store.setState({ busy: false, progress: "체크포인트 복원 완료" });
    }
  };
  return {
    store,
    async restore() {
      if (store.getState().restoring || store.getState().workspaces.length || disposed) return;
      store.setState({ restoring: true, busy: true, progress: "저장된 workspace 확인 중" });
      try {
        const restored = await repository.load();
        if (!restored?.checkpoints.length) return;
        const workspaces: Workspace[] = [];
        for (const record of restored.checkpoints.slice(0, 4)) {
          const seed = record.workspace.mode === "postgresql" ? { ...record.seed, reusePgliteDatabase: true } : record.seed;
          const client = factory(record.workspace.mode, record.workspace.id, seed);
          clients.set(record.workspace.id, client);
          bind(record.workspace.id, client, record.workspace.name, false);
          try {
            const snapshot = await client.createWorkspace();
            bind(record.workspace.id, client, record.workspace.name);
            const workspace = workspaceFromCheckpoint(record, snapshot);
            workspaces.push(workspace);
            if (workspace.file && snapshot.files.includes(workspace.file)) {
              const content = await client.readFile(workspace.file);
              workspace.drafts[workspace.file] = { text: content, saved: content };
            }
          } catch (error) {
            workspaces.push({ ...workspaceFromCheckpoint(record), broken: true, stale: true, error: runtimeFault(error) });
          }
        }
        const ids = new Set(workspaces.map((workspace) => workspace.id));
        const collaboration = restored.session.collaboration &&
          [restored.session.collaboration.baseId, restored.session.collaboration.aliceId, restored.session.collaboration.bobId, restored.session.collaboration.integrationId].every((id) => ids.has(id))
          ? restored.session.collaboration : undefined;
        entryId = Math.max(0, ...workspaces.flatMap((workspace) => workspace.entries.map((entry) => entry.id)));
        workspaceNumber = workspaces.length;
        store.setState({ workspaces, activeId: ids.has(restored.session.activeId ?? "") ? restored.session.activeId : workspaces[0]?.id,
          panel: restored.session.panel, guideEnabled: restored.session.guideEnabled, activeLesson: restored.session.activeLesson,
          collaboration, progress: `${workspaces.length}개 workspace 복원 완료` });
      } catch (error) {
        store.setState({ progress: `저장 상태를 복원하지 못했습니다: ${error instanceof Error ? error.message : String(error)}` });
      } finally { store.setState({ restoring: false, busy: false }); }
    },
    async create(mode: DatabaseMode) {
      if (store.getState().busy || clients.size >= 4) return;
      const id = `${mode}-${crypto.randomUUID()}`;
      const number = ++workspaceNumber;
      const client = factory(mode, id);
      clients.set(id, client);
      bind(id, client);
      store.setState((state) => ({ activeId: id, workspaces: [...state.workspaces, {
        id, name: `${mode === "sqlite" ? "SQLite" : "PostgreSQL"} ${number}`,
        mode, drafts: {}, entries: [], changes: [], broken: false, stale: false, evidence: emptyLessonEvidence(),
      }] }));
      await perform(async () => { patch(id, { snapshot: await client.createWorkspace() }); await checkpoint(id); });
    },
    select(id: string) { if (!store.getState().busy) { store.setState({ activeId: id }); void saveSession(); } },
    async reset() {
      const workspace = active();
      if (!workspace || store.getState().busy) return;
      const collaboration = store.getState().collaboration;
      const linked = collaboration && [collaboration.baseId, collaboration.aliceId, collaboration.bobId, collaboration.integrationId].includes(workspace.id)
        ? new Set([collaboration.baseId, collaboration.aliceId, collaboration.bobId, collaboration.integrationId])
        : new Set([workspace.id]);
      store.setState({ busy: true, progress: "Workspace 파일·DB·체크포인트 삭제 중" });
      for (const id of linked) {
        const client = clients.get(id);
        try { if (client?.destroy) await client.destroy(); else client?.close(); } catch { client?.close(); }
        clients.delete(id);
      }
      store.setState((state) => ({ workspaces: state.workspaces.filter((item) => !linked.has(item.id)), activeId: undefined,
        collaboration: linked.size > 1 ? undefined : state.collaboration }));
      await enqueuePersistence(() => repository.delete([...linked], session()));
      store.setState({ busy: false });
      await this.create(workspace.mode);
    },
    guide(enabled: boolean) { store.setState({ guideEnabled: enabled }); void saveSession(); },
    lesson(lesson: LessonId) { store.setState({ activeLesson: lesson, guideEnabled: true }); void saveSession(); },
    panel(panel: Panel) { store.setState({ panel }); void saveSession(); },
    edit(text: string) {
      const workspace = active();
      if (!workspace?.file || store.getState().busy || workspace.broken) return;
      const draft = workspace.drafts[workspace.file];
      if (draft) patch(workspace.id, { drafts: { ...workspace.drafts, [workspace.file]: { ...draft, text } } });
    },
    openFile(path: string) {
      store.setState({ panel: "editor" });
      return perform(async (workspace, client) => {
        const revision = workspace.snapshot?.revisions.find((node) => node.path === path)?.revision;
        const evidence = recordRevisionReview(workspace.evidence, revision);
        patch(workspace.id, { revision, evidence });
        await loadFile(workspace, client, path);
        if (evidence !== workspace.evidence) await checkpoint(workspace.id);
        else await saveSession();
      });
    },
    selectRevision(revision: string) {
      const workspace = active();
      const path = workspace?.snapshot?.revisions.find((node) => node.revision === revision)?.path;
      if (path) return this.openFile(path);
    },
    save() {
      return perform(async (workspace, client) => {
        const path = workspace.file;
        if (!path) return;
        const draft = workspace.drafts[path];
        if (!draft) return;
        const result = await client.writeFile(path, draft.text);
        patch(workspace.id, { snapshot: result.state, changes: result.fileChanges, stale: false, data: undefined,
          drafts: { ...workspace.drafts, [path]: { text: draft.text, saved: draft.text } } });
        await checkpoint(workspace.id);
      });
    },
    run(command: string) {
      return perform(async (workspace, client) => {
        const id = ++entryId;
        try {
          const result = await client.runCommand(command);
          patch(workspace.id, { result, snapshot: result.after, changes: result.fileChanges, data: undefined, stale: false,
            error: result.error, evidence: recordCommandEvidence(workspace.evidence, result),
            entries: [...workspace.entries, { id, command, result }].slice(-100) });
          const path = result.fileChanges.find((file) => file.change !== "deleted" && result.after.revisions.some((node) => node.path === file.path))?.path
            ?? (workspace.file && result.after.files.includes(workspace.file) ? workspace.file : result.after.files.find((file) => file === "models.py"));
          if (path) {
            await loadFile(workspace, client, path, true);
            const revision = result.after.revisions.find((node) => node.path === path)?.revision;
            const latest = store.getState().workspaces.find((item) => item.id === workspace.id);
            patch(workspace.id, { revision, evidence: recordRevisionReview(latest?.evidence ?? workspace.evidence, revision) });
          } else patch(workspace.id, { file: undefined, revision: undefined });
          if (result.success) await checkpoint(workspace.id);
        } catch (error) {
          const fault = fail(workspace.id, error);
          patch(workspace.id, { entries: [...workspace.entries, { id, command, error: fault }].slice(-100) });
        }
      });
    },
    table(table: string) {
      store.setState({ panel: "database" });
      return perform(async (workspace, client) => {
        patch(workspace.id, { table, data: undefined });
        patch(workspace.id, { data: await client.readTable(table) });
      });
    },
    async exportArchive(): Promise<{ blob: Blob; filename: string } | undefined> {
      const workspace = active();
      const client = workspace && clients.get(workspace.id);
      if (!workspace || !client || workspace.broken || store.getState().busy || Object.values(workspace.drafts).some((draft) => draft.text !== draft.saved)) return undefined;
      store.setState({ busy: true, progress: "Workspace archive 생성 중" });
      try {
        const seed = await client.exportClone();
        const database = workspace.mode === "sqlite"
          ? { format: "sqlite-file" as const, content: base64ToArrayBuffer(seed.sqliteDatabase ?? "") }
          : { format: "pglite-datadir" as const, content: seed.pgliteDatabase instanceof Blob
            ? await seed.pgliteDatabase.arrayBuffer() : seed.pgliteDatabase ?? new ArrayBuffer(0) };
        const blob = await createWorkspaceArchive({ formatVersion: 1, workspace: { id: workspace.id, name: workspace.name, mode: workspace.mode },
          files: seed.files.map((file) => ({ ...file, encoding: "utf8" as const })), database, lessonProgress: encodeEvidence(workspace.evidence) });
        return { blob, filename: `${workspace.name.toLowerCase().replace(/[^a-z0-9가-힣]+/g, "-") || "revision-lab"}.revision-lab.zip` };
      } catch (error) {
        patch(workspace.id, { error: persistenceFault(error, "ARCHIVE_EXPORT_FAILED") });
        return undefined;
      } finally { store.setState({ busy: false, progress: "Archive 생성 완료" }); }
    },
    async importArchive(archive: WorkspaceArchiveV1): Promise<void> {
      if (store.getState().busy || clients.size >= 4) return;
      const id = `${archive.workspace.mode}-${crypto.randomUUID()}`;
      const seed: RuntimeCloneSeed = { files: archive.files.map((file) => ({ path: file.path, content: file.content })) };
      if (archive.workspace.mode === "sqlite") seed.sqliteDatabase = arrayBufferToBase64(archive.database.content);
      else seed.pgliteDatabase = new Blob([archive.database.content], { type: "application/gzip" });
      const client = factory(archive.workspace.mode, id, seed);
      clients.set(id, client);
      bind(id, client);
      const number = ++workspaceNumber;
      const imported: Workspace = { id, name: `${archive.workspace.name || `Workspace ${number}`} · 가져옴`, mode: archive.workspace.mode,
        drafts: {}, entries: [], changes: [], broken: false, stale: false, evidence: decodeEvidence(archive.lessonProgress) };
      store.setState((state) => ({ activeId: id, workspaces: [...state.workspaces, imported] }));
      await perform(async () => { patch(id, { snapshot: await client.createWorkspace() }); await checkpoint(id); });
    },
    async setupCollaboration() {
      const source = active();
      if (!source || store.getState().busy || store.getState().collaboration) return;
      const sourceClient = clients.get(source.id);
      const dirty = Object.values(source.drafts).some((draft) => draft.text !== draft.saved);
      if (!sourceClient || clients.size !== 1 || dirty || !canCloneCollaborationBase(source.snapshot)) {
        patch(source.id, { error: { code: "COLLABORATION_BASE_NOT_READY", message: "하나의 workspace에서 저장하지 않은 편집 없이, 하나의 head까지 upgrade한 상태를 공통 base로 준비하세요." } });
        return;
      }
      store.setState({ busy: true, progress: "공통 base의 파일과 실제 DB를 복제하는 중" });
      const created: Array<{ id: string; client: LabClient }> = [];
      try {
        const seed = await sourceClient.exportClone();
        const collaborationId = `collab-${crypto.randomUUID()}`;
        const roles = [
          { role: "alice" as const, name: "Alice branch" },
          { role: "bob" as const, name: "Bob branch" },
          { role: "integration" as const, name: "Integration" },
        ];
        const clones: Workspace[] = [];
        for (const item of roles) {
          const id = `${source.mode}-${item.role}-${crypto.randomUUID()}`;
          const client = factory(source.mode, id, seed);
          created.push({ id, client });
          clients.set(id, client);
          bind(id, client, item.name);
          clones.push({ id, name: item.name, mode: source.mode, drafts: {}, entries: [], changes: [], broken: false, stale: false,
            evidence: emptyLessonEvidence(), role: item.role, collaborationId, snapshot: await client.createWorkspace() });
        }
        const [alice, bob, integration] = clones;
        if (!alice || !bob || !integration) throw new Error("Collaboration clone creation failed");
        patch(source.id, { name: "공통 Base", role: "base", collaborationId, error: undefined });
        store.setState((state) => ({
          workspaces: [...state.workspaces, ...clones], activeId: alice.id,
          collaboration: { id: collaborationId, baseId: source.id, baseRevisions: source.snapshot!.revisions.map((revision) => revision.revision),
            aliceId: alice.id, bobId: bob.id, integrationId: integration.id, filesIntegrated: false, multipleHeadsObserved: false },
        }));
        for (const workspace of [source, ...clones]) await checkpoint(workspace.id);
      } catch (error) {
        for (const item of created) { item.client.close(); clients.delete(item.id); }
        patch(source.id, { error: runtimeFault(error) });
      } finally {
        store.setState({ busy: false, progress: "협업 workspace 준비 완료" });
      }
    },
    async integrateBranches() {
      const collaboration = store.getState().collaboration;
      if (!collaboration || store.getState().busy || collaboration.filesIntegrated) return;
      const state = store.getState();
      const alice = state.workspaces.find((workspace) => workspace.id === collaboration.aliceId);
      const bob = state.workspaces.find((workspace) => workspace.id === collaboration.bobId);
      const integration = state.workspaces.find((workspace) => workspace.id === collaboration.integrationId);
      const integrationClient = clients.get(collaboration.integrationId);
      const base = new Set(collaboration.baseRevisions);
      const actorBranchFiles = [alice, bob].map((actor) => actor?.snapshot?.revisions
        .filter((revision) => !base.has(revision.revision) && revision.path)
        .map((revision) => ({ actor: actor!, path: revision.path! })) ?? []);
      const branchFiles = actorBranchFiles.flat();
      if (!alice || !bob || !integration || !integrationClient ||
        [alice, bob].some((actor) => Object.values(actor.drafts).some((draft) => draft.text !== draft.saved)) ||
        actorBranchFiles.some((files) => files.length === 0)) {
        if (integration) patch(integration.id, { error: { code: "BRANCHES_NOT_READY", message: "Alice와 Bob이 각자 revision을 만들고 편집을 저장한 뒤 PR을 합치세요." } });
        return;
      }
      if (new Set(branchFiles.map((item) => item.path)).size !== branchFiles.length) {
        patch(integration.id, { error: { code: "REVISION_FILE_CONFLICT", message: "같은 경로의 revision 파일이 있어 자동으로 합칠 수 없습니다." } });
        return;
      }
      store.setState({ busy: true, progress: "Alice와 Bob의 revision 파일을 integration에 합치는 중", activeId: integration.id });
      try {
        let snapshot = integration.snapshot;
        const changes: FileChange[] = [];
        for (const item of branchFiles) {
          const sourceClient = clients.get(item.actor.id);
          if (!sourceClient) throw new Error(`Missing runtime for ${item.actor.name}`);
          const content = await sourceClient.readFile(item.path);
          const written = await integrationClient.writeFile(item.path, content);
          snapshot = written.state;
          changes.push(...written.fileChanges);
        }
        patch(integration.id, { snapshot, changes, error: undefined, stale: false });
        store.setState({ collaboration: { ...collaboration, filesIntegrated: true,
          multipleHeadsObserved: (snapshot?.revisions.filter((revision) => revision.isHead).length ?? 0) > 1 }, panel: "graph" });
        await checkpoint(integration.id);
      } catch (error) {
        patch(integration.id, { error: runtimeFault(error) });
      } finally {
        store.setState({ busy: false, progress: "Integration graph 확인 완료" });
      }
    },
    recover() { const workspace = active(); if (workspace) return recoverWorkspace(workspace.id); },
    forceCrashForTest() { const workspace = active(); if (workspace) clients.get(workspace.id)?.forceCrashForTest?.(); },
    dispose() { disposed = true; clients.forEach((client) => client.close()); clients.clear(); },
  };
}
export type Lab = ReturnType<typeof createLab>;
